# Generated by Django 4.2.4 on 2024-02-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='asd',
        ),
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
